import { EditorView } from '@codemirror/view'
import { HighlightStyle, syntaxHighlighting } from '@codemirror/language'
import { tags as t } from '@lezer/highlight'

/**
 * Colours come from the app's CSS variables so the editor follows the
 * light / dark theme automatically.
 */
export const editorTheme = EditorView.theme({
  '&': {
    height: '100%',
    fontSize: 'var(--editor-font-size, 16px)',
    backgroundColor: 'transparent',
    color: 'var(--foreground)',
  },
  '&.cm-focused': { outline: 'none' },
  '.cm-scroller': {
    fontFamily: 'var(--font-sans)',
    lineHeight: '1.7',
    overflow: 'auto',
  },
  '.cm-content': {
    maxWidth: '760px',
    margin: '0 auto',
    padding: '96px 32px 240px',
    caretColor: 'var(--primary)',
  },
  '.cm-line': { padding: '0' },
  '.cm-cursor, .cm-dropCursor': { borderLeftColor: 'var(--primary)', borderLeftWidth: '2px' },
  '&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, .cm-selectionBackground': {
    backgroundColor: 'color-mix(in oklch, var(--primary) 28%, transparent)',
  },
  '.cm-activeLine': { backgroundColor: 'transparent' },
  '.cm-gutters': { display: 'none' },

  // ----- block styles -----
  '.cm-h1, .cm-h2, .cm-h3, .cm-h4, .cm-h5, .cm-h6': { fontWeight: '700', lineHeight: '1.3' },
  '.cm-h1': { fontSize: '2em', paddingTop: '0.4em', paddingBottom: '0.3em' },
  '.cm-h2': { fontSize: '1.5em', paddingTop: '0.9em', paddingBottom: '0.25em' },
  '.cm-h3': { fontSize: '1.25em', paddingTop: '0.7em', paddingBottom: '0.2em' },
  '.cm-h4': { fontSize: '1.1em', paddingTop: '0.5em' },
  '.cm-h5, .cm-h6': { fontSize: '1em', paddingTop: '0.4em' },
  '.cm-header-mark': {
    color: 'var(--muted-foreground)',
    fontWeight: '400',
    opacity: '0.7',
    marginRight: '0.35em',
  },
  '.cm-blockquote': {
    borderLeft: '3px solid color-mix(in oklch, var(--primary) 70%, transparent)',
    paddingLeft: '1em',
    color: 'var(--muted-foreground)',
    fontStyle: 'italic',
  },
  '.cm-codeblock': {
    backgroundColor: 'var(--code-bg)',
    fontFamily: 'var(--font-mono)',
    fontSize: '0.875em',
    lineHeight: '1.6',
    paddingLeft: '1em',
    paddingRight: '1em',
  },
  '.cm-codeblock-start': {
    borderTopLeftRadius: '8px',
    borderTopRightRadius: '8px',
    paddingTop: '0.5em',
  },
  '.cm-codeblock-end': {
    borderBottomLeftRadius: '8px',
    borderBottomRightRadius: '8px',
    paddingBottom: '0.5em',
  },
  '.cm-codeblock-fence': { color: 'var(--muted-foreground)', opacity: '0.7' },
  '.cm-code-lang': {
    float: 'right',
    fontSize: '0.75em',
    color: 'var(--muted-foreground)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    userSelect: 'none',
  },
  '.cm-hr-widget': {
    display: 'block',
    border: 'none',
    borderTop: '1px solid var(--border)',
    margin: '0.6em 0',
  },
  '.cm-list-bullet': {
    display: 'inline-block',
    width: '1.4em',
    color: 'var(--muted-foreground)',
    textAlign: 'center',
  },
  '.cm-list-mark': { color: 'var(--muted-foreground)' },
  '.cm-task-checkbox': {
    appearance: 'none',
    width: '1.05em',
    height: '1.05em',
    border: '1.5px solid var(--muted-foreground)',
    borderRadius: '5px',
    verticalAlign: '-0.15em',
    marginRight: '0.5em',
    cursor: 'pointer',
    position: 'relative',
    backgroundColor: 'transparent',
  },
  '.cm-task-checkbox:checked': {
    backgroundColor: 'var(--primary)',
    borderColor: 'var(--primary)',
  },
  '.cm-task-checkbox:checked::after': {
    content: '""',
    position: 'absolute',
    left: '0.3em',
    top: '0.08em',
    width: '0.3em',
    height: '0.55em',
    border: 'solid var(--primary-foreground)',
    borderWidth: '0 2px 2px 0',
    transform: 'rotate(45deg)',
  },
  '.cm-task-done': { color: 'var(--muted-foreground)', textDecoration: 'line-through' },
  '.cm-table-line': { fontFamily: 'var(--font-mono)', fontSize: '0.9em' },

  // ----- inline styles -----
  '.cm-inline-code': {
    fontFamily: 'var(--font-mono)',
    fontSize: '0.875em',
    backgroundColor: 'var(--code-bg)',
    padding: '0.15em 0.4em',
    borderRadius: '4px',
  },
  '.cm-link-rendered': {
    color: 'var(--link)',
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
    textDecorationColor: 'color-mix(in oklch, var(--link) 45%, transparent)',
    cursor: 'pointer',
  },
  '.cm-link-external': {
    color: 'var(--link-external)',
    textDecorationStyle: 'dotted',
    textDecorationColor: 'color-mix(in oklch, var(--link-external) 60%, transparent)',
  },
  '.cm-link-external::after': {
    content: '"↗"',
    fontSize: '0.7em',
    marginLeft: '0.15em',
    verticalAlign: 'super',
    opacity: '0.7',
  },
  '.cm-hashtag': {
    color: 'var(--link)',
    backgroundColor: 'color-mix(in oklch, var(--link) 12%, transparent)',
    padding: '0.05em 0.35em',
    borderRadius: '999px',
    fontSize: '0.9em',
  },
  '.cm-syntax-mark': { color: 'var(--muted-foreground)', opacity: '0.6' },
  '.cm-math-inline': {
    padding: '0 0.15em',
  },
  '.cm-math-block': {
    display: 'block',
    textAlign: 'center',
    padding: '0.5em 0',
    overflowX: 'auto',
  },
  '.cm-math-error': { color: 'var(--destructive)', fontFamily: 'var(--font-mono)', fontSize: '0.85em' },
  '.cm-mermaid-widget': {
    display: 'flex',
    justifyContent: 'center',
    padding: '1em',
    margin: '0.5em 0',
    backgroundColor: 'var(--code-bg)',
    borderRadius: '8px',
    cursor: 'text',
  },
  '.cm-mermaid-widget svg': { maxWidth: '100%', height: 'auto' },
  '.cm-image-widget': {
    display: 'block',
    maxWidth: '100%',
    borderRadius: '8px',
    margin: '0.5em 0',
  },
  '.cm-image-broken': {
    color: 'var(--destructive)',
    fontSize: '0.85em',
    fontFamily: 'var(--font-mono)',
  },
  '.cm-frontmatter': {
    color: 'var(--muted-foreground)',
    fontFamily: 'var(--font-mono)',
    fontSize: '0.85em',
  },

  // ----- autocomplete / search panels -----
  '.cm-tooltip': {
    backgroundColor: 'var(--popover)',
    color: 'var(--popover-foreground)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    boxShadow: '0 8px 24px rgb(0 0 0 / 0.25)',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul': { fontFamily: 'var(--font-sans)', fontSize: '0.9em' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li': { padding: '4px 10px' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]': {
    backgroundColor: 'var(--accent)',
    color: 'var(--accent-foreground)',
  },
  '.cm-completionIcon': { display: 'none' },
  '.cm-panels': {
    backgroundColor: 'var(--popover)',
    color: 'var(--popover-foreground)',
    borderColor: 'var(--border)',
  },
  '.cm-panels.cm-panels-bottom': { borderTop: '1px solid var(--border)' },
  // ----- in-note search panel (Ctrl+F) -----
  '.cm-panel.cm-search': {
    padding: '10px 40px 10px 16px',
    fontFamily: 'var(--font-sans)',
    fontSize: '13px',
    lineHeight: '1.4',
  },
  '.cm-panel.cm-search input': {
    appearance: 'none',
    backgroundColor: 'var(--accent)',
    color: 'var(--foreground)',
    border: '1px solid transparent',
    borderRadius: '6px',
    padding: '4px 10px',
    margin: '2px 6px 2px 0',
    minWidth: '220px',
    outline: 'none',
    fontFamily: 'inherit',
    fontSize: '13px',
  },
  '.cm-panel.cm-search input:focus': { borderColor: 'var(--primary)' },
  '.cm-panel.cm-search input::placeholder': { color: 'var(--muted-foreground)' },
  '.cm-panel.cm-search button': {
    appearance: 'none',
    backgroundColor: 'var(--secondary)',
    backgroundImage: 'none',
    color: 'var(--secondary-foreground)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    padding: '4px 10px',
    margin: '2px 4px 2px 0',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: '12px',
    textTransform: 'none',
  },
  '.cm-panel.cm-search button:hover': { backgroundColor: 'var(--accent)', color: 'var(--accent-foreground)' },
  '.cm-panel.cm-search button[name=close]': {
    position: 'absolute',
    top: '8px',
    right: '10px',
    width: '24px',
    height: '24px',
    padding: '0',
    border: 'none',
    backgroundColor: 'transparent',
    color: 'var(--muted-foreground)',
    fontSize: '18px',
  },
  '.cm-panel.cm-search label': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    marginRight: '10px',
    color: 'var(--muted-foreground)',
    fontSize: '12px',
    userSelect: 'none',
  },
  '.cm-panel.cm-search input[type=checkbox]': {
    appearance: 'auto',
    accentColor: 'var(--primary)',
    minWidth: '0',
    margin: '0',
    padding: '0',
  },
  '.cm-searchMatch': { backgroundColor: 'color-mix(in oklch, var(--primary) 30%, transparent)' },
  '.cm-searchMatch.cm-searchMatch-selected': {
    backgroundColor: 'color-mix(in oklch, var(--primary) 55%, transparent)',
  },
})

export const highlightStyle = HighlightStyle.define([
  { tag: t.heading, fontWeight: '700' },
  { tag: t.strong, fontWeight: '700' },
  { tag: t.emphasis, fontStyle: 'italic' },
  { tag: t.strikethrough, textDecoration: 'line-through', color: 'var(--muted-foreground)' },
  { tag: t.link, color: 'var(--link)' },
  { tag: t.url, color: 'var(--muted-foreground)' },
  { tag: t.processingInstruction, color: 'var(--muted-foreground)' },
  { tag: t.contentSeparator, color: 'var(--muted-foreground)' },
  { tag: t.labelName, color: 'var(--link)' },
  { tag: t.escape, color: 'var(--muted-foreground)' },
  { tag: t.monospace, fontFamily: 'var(--font-mono)' },

  // code block highlighting (nested languages)
  { tag: t.keyword, color: 'var(--syntax-keyword)' },
  { tag: [t.name, t.deleted, t.character, t.macroName], color: 'var(--syntax-name)' },
  { tag: [t.propertyName], color: 'var(--syntax-property)' },
  { tag: [t.function(t.variableName), t.labelName], color: 'var(--syntax-property)' },
  { tag: [t.color, t.constant(t.name), t.standard(t.name)], color: 'var(--syntax-constant)' },
  { tag: [t.definition(t.name), t.separator], color: 'var(--foreground)' },
  {
    tag: [t.typeName, t.className, t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace],
    color: 'var(--syntax-type)',
  },
  { tag: [t.operator, t.operatorKeyword, t.regexp, t.special(t.string)], color: 'var(--syntax-operator)' },
  { tag: [t.meta, t.comment], color: 'var(--muted-foreground)', fontStyle: 'italic' },
  { tag: t.atom, color: 'var(--syntax-constant)' },
  { tag: t.bool, color: 'var(--syntax-constant)' },
  { tag: [t.string, t.inserted], color: 'var(--syntax-string)' },
  { tag: t.invalid, color: 'var(--destructive)' },
])

export const editorHighlighting = syntaxHighlighting(highlightStyle)
